title: Isaac Vergara
description: Showcasing my projects, sharing my knowledge, and connecting with like-minded individuals.
show_downloads: false
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
logo: /assets/images/profile.jpg